---
title: "Predicting Student Performance"
author: "John Russell"
date: "2023-01-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The goal of this project is to gain insights on classroom performance. We will begin with a series of visualizations and conclude with a predictive model. 

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(patchwork)
library(tidyverse)
score_data <- read.csv('StudentsPerformance.csv', header = TRUE)
attach(score_data)
```

### We will begin by examining the distribution of subject specific scores across gender.

```{r echo=FALSE, message=FALSE, warning=FALSE}
male_score_data <- filter(score_data, gender == 'male')

female_score_data <- filter(score_data, gender == 'female')

#### MATH SCORES
male_math <-
        ggplot(male_score_data, aes(x = math.score)) + geom_histogram(
                aes(y = ..density..),
                binwidth = 2,
                fill = 'darkblue',
                color = 'black',
                alpha = .4
        ) +
        labs(x = "Math Score", y = "Count", title = 'Male Math') +
        geom_density(alpha = .2, fill = 'blue') +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_x_continuous(breaks = seq(0, 100, 25))

female_math <-
        ggplot(female_score_data, aes(x = math.score)) + geom_histogram(
                aes(y = ..density..),
                binwidth = 2,
                fill = 'red',
                color = 'black',
                alpha = .4
        ) +
        labs(x = "Math Score", y = "Count", title = 'Female Math') +
        geom_density(alpha = .2, fill = 'pink')  +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_x_continuous(breaks = seq(0, 100, 25))




#### READING SCORES
male_reading <-
        ggplot(male_score_data, aes(x = reading.score)) + geom_histogram(
                aes(y = ..density..),
                binwidth = 2,
                fill = 'darkblue',
                color = 'black',
                alpha = .4
        ) +
        labs(x = "Reading Score", y = "Count", title = 'Male Reading') +
        geom_density(alpha = .2, fill = 'blue')  +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_x_continuous(breaks = seq(0, 100, 25))

female_reading <-
        ggplot(female_score_data, aes(x = reading.score)) + geom_histogram(
                aes(y = ..density..),
                binwidth = 2,
                fill = 'red',
                color = 'black',
                alpha = .4
        ) +
        labs(x = "Reading Score", y = "Count", title = 'Female Reading') +
        geom_density(alpha = .2, fill = 'pink')  +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_x_continuous(breaks = seq(0, 100, 25))




#### WRITING SCORES

male_writing <-
        ggplot(male_score_data, aes(x = writing.score)) + geom_histogram(
                aes(y = ..density..),
                binwidth = 2,
                fill = 'darkblue',
                color = 'black',
                alpha = .4
        ) +
        labs(x = "Writing Score", y = "Count", title = 'Male Writing') +
        geom_density(alpha = .2, fill = 'blue')  +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_x_continuous(breaks = seq(0, 100, 25))

female_writing <-
        ggplot(female_score_data, aes(x = writing.score)) + geom_histogram(
                aes(y = ..density..),
                binwidth = 2,
                fill = 'red',
                color = 'black',
                alpha = .4
        ) +
        labs(x = "Writing Score", y = "Count", title = 'Female Writing') +
        geom_density(alpha = .2, fill = 'pink')  +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_x_continuous(breaks = seq(0, 100, 25))




# PLOTS

plots_arranged <-
        (male_math | female_math) /
        (male_reading | female_reading) /
        (male_writing |
                 female_writing) + plot_annotation(theme = theme_gray(base_family = 'mono'),
                                                   title = "Distribution of Scores across Gender")

plots_arranged
```

```{r}
male_score_data %>% summarise(Math_Average = mean(math.score), Reading_Average = mean(reading.score)) %>% tibble()

```

